# SEE: https://github.com/gitleaks/gitleaks/#configuration

[extend]
useDefault = true # SEE: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[[rules]]
description = "IPv4"
id = "ipv4"
regex = '''[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''

[rules.allowlist]
regexTarget = "match"
regexes = [
  # Exclude the private network IPv4 addresses as well as the DNS servers for Google and OpenDNS
  '''(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3}|0\.0\.0\.0|255\.255\.255\.255|8\.8\.8\.8|8\.8\.4\.4|208\.67\.222\.222|208\.67\.220\.220)''',
]

[allowlist]
files = ['.terraform.lock.hcl', 'poetry.lock', 'yarn.lock']
Regexes = '''========================================='''

[[rules]]
description = "DynamoDB Endpoints"
id = "dynamodb"
regex = '''dynamodb\.[a-z]{2}[a-z-]*[1,2,3]\.amazonaws\.com'''

[[rules]]
description = "ARN Generic"
id = "arn"
regex = '''arn:aws:(.*):(.*):[0-9]{12}'''

[[rules]]
description = "ARN S3 "
id = "arns3"
regex = '''arn:aws:s3:::(.*)'''

[[rules]]
description = "ECR Endpoints"
id = "ecr"
regex = '''[0-9]{12}\.dkr\.ecr\.[a-z-]*-[1,2,3]\.amazonaws\.com'''

[[rules]]
description = "Elastic Search Endpoints"
id = "esendpoints"
regex = '''(.*)[a-z-]*[1,2,3]\.es\.amazonaws\.com'''

[[rules]]
description = "Standard Certificate"
id = "standardcertificate"
regex = '''-----BEGIN(\s)CERTIFICATE-----\n'''

[[rules]]
description = "Private Keys"
id = "privatekeys"
regex = '''\s*(\bBEGIN\b).*(PRIVATE KEY\b)\s*'''

[[rules]]
description = "AWS Secret Access Key"
id = "secretaccesskey"
regex = '''(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)?\s*(:|=>|=)\s*[A-Za-z0-9/\+=]{40}\n'''

[[rules]]
id = "genericawsacno"
description = "Generic 12 digit AWS acccount number"
regex = '''\b\d{12}\b'''

[[rules]]
id = "awsaccountid"
description = "AWS Account ID"
regex = '''(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?\s*(:|=>|=)\s*[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}'''
