name: Validate terraform

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:

  derive-tf-versions:
    name: Derive Max Terraform Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@main
        with:
          directory: ./infrastructure/remote
    outputs:
      maxVersion: ${{ steps.minMax.outputs.maxVersion }}

  validate-against-tf-versions:
    name: Validate terraform against the min/max versions
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    permissions:
      id-token: write
      contents: read
    needs: derive-tf-versions
    strategy:
      matrix:
        stack:
          - github-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/uec-dos-user-interfaces-github-runner
          role-session-name: github-pipeline-session
          aws-region: eu-west-2

      - name: Install Terraform v${{ needs.derive-tf-versions.outputs.maxVersion }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ needs.derive-tf-versions.outputs.maxVersion }}

      - name: Initialize terraform and validate stack ${{ matrix.stack }} against v${{ needs.derive-tf-versions.outputs.maxVersion }}
        run: |
          export ACTION=validate
          export STACK=${{ matrix.stack }}
          export ACCOUNT_TYPE=${{ vars.ACCOUNT_TYPE }}
          /bin/bash ./scripts/infra-deploy.sh
